

/*  自动程序数组
typedef struct Walk_Knead_Knock_Motor_Struct_Auto
{
  //1st byte
  unsigned char nSubFunction ;////子功能索引(用于显示),  //KNEAD,KNOCK,PRESS,WAVELET,PREPARE
  unsigned char nWalkMotorLocateMethod ;// //行走电机定位方式,//0:WALK_LOCATE_ABSULATE:由绝对坐标决定 //1:WALK_LOCATE_SHOULDER:由肩部位置决定
  //2nd byte
  unsigned short nWalkMotorLocateParam;  //长行程//行走电机定位的绝对坐标或在PARK时的停顿时间


  //3rd byte
  unsigned nKneadMotorState:4 ;////KNEAD_STOP,	KNEAD_STOP_AT_MIN,/KNEAD_STOP_AT_MED,KNEAD_STOP_AT_MAX
  unsigned nKneadMotorCycles:4 ;//揉捏圈数



  //4th byte(KNOCK_STOP,KNOCK_RUN_WIDTH,KNOCK_RUN,KNOCK_RUN_STOP,KNOCK_RUN_MUSIC)	
  //Only 4 states for auto mode
  unsigned nKnockMotorState:2 ;//// //敲打电机要达到的状态, //KNOCK_STOP/KNOCK_RUN_WIDTH/KNOCK_RUN/KNOCK_RUN_STOP
  unsigned nKnockMotorRunTime:6 ;//敲打持续的时间
  //5th byte
  unsigned nKnockMotorStopTime:5 ;//敲打停顿的时间

  //unsigned nAxisMotorPosition ;//敲打停顿的时间


  unsigned nKneadKnockSpeed:3 ;//揉敲速度

  unsigned char n3D_MotorState;
  unsigned char n3D_MotorPosition;
  unsigned char n3D_MotorSpeed;
  unsigned char n3D_MotorStopTime;
} WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO ;

#define WALK_LOCATE_ABSULATE			0   //由绝对坐标决定
#define WALK_LOCATE_SHOULDER			3  //肩膀位置
#define WALK_LOCATE_TOP				2//由上端行程开关决定
#define WALK_LOCATE_SHOULDER_OR_ABSULATE	1//由肩部位置和绝对坐标中的较小者决定
#define WALK_LOCATE_PARK			4//停留在当前位置
//#define WALK_LOCATE_NeckSwitch			5
#define WALK_LOCATE_NeckMed			6  //脖子中间位置
#define WALK_LOCATE_PressNeck			7  //脖子靠近肩膀位置

#define WALK_LOCATE_WAIST             8
#define WALK_SHOULDER_WAIST_1_10      9  //肩膀向腰的位置移动1/10的距离
#define WALK_SHOULDER_WAIST_2_10      10 //肩膀向腰的位置移动2/10的距离
#define WALK_SHOULDER_WAIST_3_10      11 //肩膀向腰的位置移动3/10的距离
#define WALK_SHOULDER_WAIST_4_10      12 //肩膀向腰的位置移动4/10的距离
#define WALK_SHOULDER_WAIST_5_10      13 //肩膀向腰的位置移动5/10的距离
#define WALK_SHOULDER_WAIST_6_10      14 //肩膀向腰的位置移动6/10的距离
#define WALK_SHOULDER_WAIST_7_10      15 //肩膀向腰的位置移动7/10的距离
#define WALK_SHOULDER_WAIST_8_10      16 //肩膀向腰的位置移动8/10的距离
#define WALK_SHOULDER_WAIST_9_10      17 //肩膀向腰的位置移动9/10的距离

  //揉捏电机描述(包含了结束条件)
  //KNEAD_STOP			0 //按摩臂停留在随机位置
  //KNEAD_STOP_AT_MIN		1 //按摩臂停留在窄的位置
  //KNEAD_STOP_AT_MED		2 //按摩臂停留在中的位置
  //KNEAD_STOP_AT_MAX		3 //按摩臂停留在宽的位置
  //KNEAD_RUN			4 //按摩臂顺时钟方向揉捏
  //KNEAD_RUN_STOP		5 //按摩臂n圈后停留在随机位置
  //KNEAD_RUN_STOP_AT_MIN       6 //按摩臂n圈后停留在窄的位置
  //KNEAD_RUN_STOP_AT_MED       7 //按摩臂n圈后停留在中的位置
  //KNEAD_RUN_STOP_AT_MAX       8 //按摩臂n圈后停留在宽的位置	



#define KNOCK_STOP		0 //停止
#define KNOCK_RUN_WIDTH		1 //宽中窄定位完成后启动
#define KNOCK_RUN		2 //无需宽中窄定位，无条件立即启动
#define KNOCK_RUN_STOP		3 //宽中窄定位完成后启动短时间后马上停止
#define KNOCK_RUN_MUSIC		4 //音乐互动模式（与宽中窄定位无关）
//------------------------------------
#define _3D_MANUAL      0   //依据用户设定3D力度动作
#define _3D_PROGRAM     1   //依据设定的3D位置动作
#define _3D_CURRENT     2   //依据电流检测位置动作
#define _3D_PARK        3   //3D马达停留在当前位置
#define AXIS_STRONGEST 4  
#define AXIS_STRONGER  3
#define AXIS_MIDDLE    2
#define AXIS_WEAKER    1
#define AXIS_WEAKEST   0

//这个参数的单位是10ms,是指脉冲宽度

#define _3D_SPEED_1 16
#define _3D_SPEED_2 15
#define _3D_SPEED_3 14
#define _3D_SPEED_4 13
#define _3D_SPEED_5 12
#define _3D_SPEED_6 11
#define _3D_SPEED_7 10
#define _3D_SPEED_8 9
#define _3D_SPEED_9 8
#define _3D_SPEED_10 7



*/

const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO AutoFunction4[] = 
{	
  

  //上提   揉捏宽度：窄 窄 揉
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed  ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP_AT_MED  ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK    ,10,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},
  
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MIN         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP_AT_MED         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,10,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},

  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MIN         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP_AT_MED         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,10,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MIN         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP_AT_MED         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MIN         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP_AT_MED         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
//
 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  
  //上提   揉捏宽度：窄
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
 //
 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MED,5,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
 
 
 
 
  //压肩  中
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  
  
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
 {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  
  //压肩  宽
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
 {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
 {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
 {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
 
  //滑肩  肩部抚摸  揉捏宽度：中
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  
 /* {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
  */
  
  //滑肩  肩部抚摸  揉捏宽度：窄
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  
  //滑肩  肩部抚摸  揉捏宽度：宽
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  
  
  
  
  //指压到顶
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MAX,1,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,40,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MAX,1,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,40,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MAX,1,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,40,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  
  //搓背  
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,1,4,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,8,2,SPEED_4,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,8,2,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,9,1,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},	
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  //肩部捶打
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN_STOP,8,2,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,7,3,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,6,4,SPEED_4,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,5,5,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,1,4,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,1,4,SPEED_6,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,8,2,SPEED_4,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,8,2,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,9,1,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,9,1,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},


  //捶击定位（窄中宽）
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //捶击定位（窄中宽）
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  /*
  //揉捶同步到底部（低速）
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  /////////////////////////////////////////////////////////////////////////////
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //1
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_TOP,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //2
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //3
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //4
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION+80,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //5
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_TOP,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //6
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION+80,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //7
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_TOP,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //8
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION+80,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //9
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_TOP,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //10
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //11
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //12
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,80,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //13
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //14
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,80,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  
  //搓背  
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  
  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,1,4,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,8,2,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,8,2,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,9,1,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},							
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_5,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_6,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,100,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,100,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  /////////////////////////////////////////////////////////////////////////////		
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  ////////////////////////////////////////////////////////////////////////////
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  //肩部捶打
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN_STOP,8,2,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,7,3,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,6,4,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,5,5,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,1,4,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,1,4,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,8,2,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,8,2,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,9,1,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,9,1,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //Neck Knead
  ////
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},		
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,5,KNEAD_RUN_STOP_AT_MAX,2,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  
  //搓背  
  //  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+25,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //揉捏
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //向上行走15，捶击定位（窄）
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+15,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  //向上行走15，捶击定位（窄）
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  //向上行走15，捶击定位（窄）80
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIS//捶击定位（窄中宽）
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //捶击定位（窄中宽）
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  T_POSITION+45,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  //向上行走15，捶击定位（窄）
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+60,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  //向下揉捏到底
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //定点轻敲5次
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,25,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  //轻敲到顶部
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_TOP,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  //定点低速揉捏5
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //向下捶击行走到肩部	////
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},		
  //定点捶击2秒
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,20,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //向上捶击行走到顶部	100
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},		
  //定点捶击2秒
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,KNOCK_STOP,20,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //向下捶击行走到肩部	
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},		
  //定点捶击2秒
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,20,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},		
  //定点揉捏5
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //向下捶击行走到底	
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,4,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //向上揉捶行走25/115
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+25,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+50,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //向下揉捏到底
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //变速揉摧同步到底
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+60,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //定点揉捏5
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //窄指压到顶
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_TOP,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  
  //070315测试/133
  //颈部动作组合
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_TOP,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},		
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},		
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},		
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},		
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},		
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //低速敲打到底部/141
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_TOP,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},		
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},		
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_NeckMed,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},		
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},		
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+80,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},		
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+40,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},		
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  
  //搓背  
  //  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  
  
  //腰部变速敲打161
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MED,5,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //行走揉摧同步182
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+40,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+80,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //颈部动作组合194
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,1,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //轻敲到肩部//208
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  //轻敲到顶部
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_TOP,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  //轻敲
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  //轻敲			////////////////////////////////////
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  //轻敲
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+60,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  //轻敲
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  //轻敲
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,25,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,25,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  //揉捏到顶/217
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+80,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //变换幅度的轻敲/222
  //轻敲到肩部
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN_STOP_AT_MED,1,KNOCK_RUN_STOP,1,4,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_TOP,0,KNEAD_RUN_STOP_AT_MIN,1,KNOCK_RUN_STOP,1,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0}
  */
};
